apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tileserver-ingress
  namespace: lonctus
spec:
  ingressClassName: traefik
  rules:
  - host: tiles.lonctus.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tileserver
            port:
              number: 80
