apiVersion: v1
data:
  config.json: |
    {
      "options": {
        "serveStaticMaps": true
      },
      "data": {
        "grid": {
          "mbtiles": "/data/grid.mbtiles"
        },
        "density": {
          "mbtiles": "/data/density.mbtiles"
        },
        "population_grid": {
          "mbtiles": "/data/population_grid.mbtiles"
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.json":"{\n  \"options\": {\n    \"serveStaticMaps\": true\n  },\n  \"data\": {\n    \"grid\": {\n      \"mbtiles\": \"/data/grid.mbtiles\"\n    },\n    \"density\": {\n      \"mbtiles\": \"/data/density.mbtiles\"\n    }\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"tileserver"},"name":"tileserver-config","namespace":"map"}}
  creationTimestamp: "2025-11-25T21:31:25Z"
  labels:
    app: tileserver
  name: tileserver-config
  namespace: map
  resourceVersion: "2111568"
  uid: dc119dbb-5f44-42b8-a98c-0792ae586f39
