apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lonctus
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kaljo14/my-map@sha256:193c3bcf43551668c48f95413cf0fdf3b96bfc5d5584f58c7eb7ef69bd828b27
          env:
            - name: ENABLE_AUTH
              value: "true"
            - name: PLACES_API_URL
              value: "http://places-scraper"
            - name: TILES_API_URL
              value: "http://tileserver"
            - name: MARTIN_API_URL
              value: "http://martin"
          ports:
            - name: http
              containerPort: 80 # Adjust if your app listens on 3000 or 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: lonctus
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80 # Must match containerPort
      protocol: TCP
      name: http
  selector:
    app: frontend
