apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs
  namespace: lonctus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: lonctus-docs-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - docs.lonctus.com
      secretName: docs-tls
  rules:
    - host: docs.lonctus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: docs-auth
  namespace: lonctus
spec:
  basicAuth:
    secret: docs-basic-auth
    removeHeader: true
