apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        static_configs:
          - targets: [localhost]
            labels:
              job: envoy-logs
              namespace: lonctus
              __path__: /var/log/pods/lonctus_*/envoy/*.log
        pipeline_stages:
          - json:
              expressions:
                method: method
                path: path
                response_code: response_code
                duration: duration
                bytes_sent: bytes_sent
                user: user
          - labels:
              method:
              response_code:
              user:
