apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend
  - docs
  - places-scraper
  - martin
  - tileserver
labels:
  - pairs:
      managed-by: kustomize
      env: production
